# Generated by Django 2.2.16 on 2023-02-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
